name-template: "v$NEXT_PATCH"
tag-template: "v$NEXT_PATCH"
categories:
  - title: 🚀 Features
    labels:
      - "feature"
  - title: 🐛 Bug Fixes
    labels:
      - "fix"
version:
  bump-patch-labels: ["fix"]
  bump-minor-labels: ["feat"]
  bump-major-labels: ["BREAKING CHANGE"]
