name: Build and Release for Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup update stable && rustup target add x86_64-unknown-linux-gnu

      - name: Build project
        run: cargo build --release --target=x86_64-unknown-linux-gnu

      - name: Organize build artifacts
        run: |
          mkdir -p builds/linux
          mv target/x86_64-unknown-linux-gnu/release/flow builds/linux/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: builds/linux/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Draft Release with Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: builds/linux/*
          body: |
            🚀 New release generated from GitHub Actions!
            
            **Platform included:**
            - 🐧 Linux (`builds/linux/`).
